/// Generated by AssetsRefGenerator on 2020/07/05
class Res {
  static const String category = "assets/category.jpg";
  static const String scan = "assets/scan.png";
  static const String scan2 = "assets/scan2.png";
  static const String scan3 = "assets/scan3.png";
}
